[package]
authors = ["Stijn Frishert"]
description = "A set of tools for working with LSDJ files"
edition = "2021"
name = "lsdj-tools"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.56"
clap = {version = "3.0.10", features = ["derive"]}
lsdj = {path = "../lsdj"}
pathdiff = "0.2.1"
walkdir = "2.3.2"
