[package]
authors = ["Stijn Frishert <info@stijnfrishert.com>"]
description = "A set of tools for working with LSDJ files"
edition = "2021"
name = "lsdj-tools"
repository = "https://github.com/stijnfrishert/lsdj-rs"
version = "1.0.0"

[dependencies]
anyhow = "1.0.56"
clap = {version = "3.0.10", features = ["derive"]}
lsdj = {version = "1.0", path = "../lsdj"}
walkdir = "2.3.2"
wild = "2.0.4"
